### PR TITLE
Upgrade theme to 0.1.11 alongside all other packages

### PR DESCRIPTION
**Pull request by rogermparent**
https://github.com/iterative/mlem.ai/pull/141, https://github.com/iterative/dvc.org/pull/3785 are the same thing on different sites

Depends on #271 

This PR updates all our packages to the latest version, with the intent to look for and fix anything that's broken. We at the very least want the latest Gatsby, particularly for some new APIs that were introduced, but with the world of JS web packages moving at hyperspeed I think a blanket update on everything is warranted for our websites so we can bring each site and the theme to the same level of updated.

Particular attention was paid to Husky, giving each PR a `prepare` script if it wasn't present before. I'm not sure if this is a v7-v8 thing or if we just weren't properly set up before.

### CODE REVIEW

**Review by yathomasi — APPROVED** [review]
Looks good to me. It's working fine on development and builds. Guess, we are good to go.

**Comment by rogermparent** [comment]
Some of the updates, particularly React 17->18, changed how the types work and generated a few css and ts lint errors. I went and changed what was needed to satisfy tsc and eslint at the current version of everything.

**Comment by yathomasi** [comment]
Shall we add GitHub action similar for lint check as well? It can just go the same PR.

**Comment by rogermparent** [comment]
Good idea, but if we do use GH Actions we'll want to drop CircleCI as well since we're currently doing lint checks there. I think it can wait for another PR.

**Pull request merged**
