### PR TITLE
Add admonition feature

### PR DESCRIPTION
**Pull request by julieg18**
Basically a copy of [dvc.org#3371](https://github.com/iterative/dvc.org/pull/3371)

Code Example:
```
<admon type="warn">

text text text

</admon>
```

Design:

image

**Type options:**

* `info` (default emoji is ℹ️)
* `tip` (default emoji is 💡)
* `warn` (default emoji is ⚠️)

**Icon options:**

tip - 💡
info - ℹ️
warn - ⚠️
fire - 🔥
exclamation - ❗
beetle - 🐞

### CODE REVIEW

**Review by shcheklein — APPROVED** [review]

**Comment by jorgeorpinel** [comment]
> Icon options:
...
exclamation - ❗

Question @iterative/websites : why are there so many icons and which styles does each one use? E.g. looks like "exclamation" is type "warn" but with another icon. [A bit confusing](https://github.com/iterative/dvc.org/pull/3411#pullrequestreview-958511434) (minor)

**Comment by julieg18** [comment]
> Question @iterative/websites : why are there so many icons and which style does each one use? E.g. looks like "exclamation" is type "warn" but with another icon. [A bit confusing](https://github.com/iterative/dvc.org/pull/3411#pullrequestreview-958511434) (minor)

Essentially there are three type that come with their own color:
info - purple
tip -blue
warn - orange

While these come with default emojis, you can update any type to use a different icon if you'd like by using the `icon` prop. We originally just had the three emojis, but it was requested that we have extra icon options.

**Comment by jorgeorpinel** [comment]
Got it. The `icon` prop info. is what was missing. TBH so far we're not using that feature much. It's unclear to me why we would need alternative icons and those specifically. That said it doesn't hurt to keep it either.

**Comment by jorgeorpinel** [comment]
No wait... [In this PR](https://github.com/iterative/dvc.org/pull/3411#discussion_r865448839) we used `type="exclamation"` and it rendered correctly (as a type `warn` with ! icon). How does that work?

**Comment by julieg18** [comment]
> No wait... [In this PR](https://github.com/iterative/dvc.org/pull/3411#discussion_r865448839) we used `type="exclamation"` and it rendered correctly (as a type `warn` with ! icon). How does that work?

It actually didn't render as `warn`! `warn` is orange, not purple.  That's the `info` type, aka purple, because the admonition defaults to `info` if it doesn't get a type (or the type doesn't exist). 


As for how you still got the exclamation, even though the `icon` prop wasn't used. If you don't give an icon type, the `icon` defaults to `type`. Aka 
```
<admon type='warn'>
  text text text text
</admon>
```
image
Because the icon name for `warn` is ⚠️. 

We probably don't want that behavior though. I'll open a pr that stops `icon` from defaulting to `type` so there is less confusion in the future.

**Comment by jorgeorpinel** [comment]
I see.

> If you don't give an icon type, the icon defaults to type

Ok that's the unexpected part indeed. Thanks!

**Comment by casperdcl** [comment]
​Not sure extra icons not linked to type are useful. Seems to break theme/convention IMO.

**Pull request merged**
