### PR TITLE
Update site meta tags

### LINKED ISSUE #128: Review favicons, descriptions, other meta headers
E.g. it looks like favicon is too low res.

Some formats are not available according to https://realfavicongenerator.net/favicon_checker?protocol=http&site=cml.dev#.YWyLu9nMLlw (probably there are more websites like this).

We need to review all the regular fields one more time, make it a single source or truth. The same should be done to iterative.ai / dvc.org - they all should be using the same mechanism.

### PR DESCRIPTION
**Pull request by julieg18**
The meta tags looked pretty good! The only issue I found was missing image alts.

Fixes #128

### CODE REVIEW

**Comment by julieg18** [comment]
Current our twitter handle is @dvcOrg. Do we want to update this to @Iterativeai?

**Comment by shcheklein** [comment]
Thnks @julieg18 ! Please, let's check also Hexometer repots regarding metatags.

> Currently our twitter handle is @dvcOrg. Do we want to update this to @Iterativeai?

Not for now, it'a bigger discussion that is happening now if we want to migrate to @iterativeai or not.

> Do we want to go ahead and take off the "keywords" meta tag since it's not relevant anymore?

why is it not relevant anymore?

**Review by rogermparent — APPROVED** [review]

**Review by casperdcl — APPROVED** [review]

**Comment by rogermparent** [comment]
> why is [the keywords meta tag] not relevant anymore?

All the big search engines (Google, Bing, Yahoo) either do not or barely use meta keywords because they're too abusable with techniques like keyword stuffing when they're taken into account. Some smaller search engines may use them, but the benefit is very likely inconsequential at most.

Some sources:
https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag
https://www.clickminded.com/meta-keywords/
https://datadrivenlabs.io/blog/keyword-meta-tag-google/

**Comment by julieg18** [comment]
> Thanks @julieg18 ! Please, let's check also Hexometer repots regarding metatags.

How do I access hexometer?

> All the big search engines (Google, Bing, Yahoo) either do not regard or barely use meta keywords, this has been the case for a while because they're too abusable with techniques like keyword stuffing when they're taken into account. Some smaller search engines may use them, but the benefit is very likely inconsequential at most.

Correct! While most websites (Github, Youtube, Twitter etc.) don't have them, it doesn't hurt to keep them if we prefer. The only reason I was asking was so that we could decide if our "single source" (referencing #128) will include a keywords meta tag or not.

**Comment by shcheklein** [comment]
> How do I access hexometer?

I've invited you.

> keywords

SEO - makes sense. Are there any other scenarios/tools that use keywords for some reason?

**Comment by julieg18** [comment]
> SEO - makes sense. Are there any other scenarios/tools that use keywords for some reason?

Not that I can find.

**Comment by julieg18** [comment]
Hexometer reports:

image

* `og:image:url` - same thing as `og:image` which we already have
* `og:image:secure_url` - only needed if your `og:image` is not secure
* `og:image:type` - This one is optional and since all of our social media previews were working, I figured we didn't need it. I can go ahead and add it though. 
* `og:locale` - meta tag for telling what languages your site is available in. The default is english and since that is what our site is, I figured we didn't need it. But I can add it. 
* `fb:app_id` - only needed if we want to use Facebook analytics. 

image

* `twitter:creator` - only needed if you are using a `summary_large_image` twitter card which cml.dev does not.
* `twitter:image:alt` - added 😃 
* `twitter:player` - only needed if we wanted to use a player twitter card instead of an image card

**Pull request merged**
