### PR TITLE
minor formatting

### PR DESCRIPTION
**Pull request by casperdcl**
`yaml` :arrow_right: `dvc`

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]
🙏🏼 🎉 :shipit:

**Comment by casperdcl** [comment]
merge! sudo merge! What do you mean I can't merge my own PR?

xkcd#149

**Comment by 0x2b3bfa0** [comment]
This repository is configured to require an approval from another user before merging. 🤷🏼  Probably so we can't deface our own web pages? 🙃

**Comment by casperdcl** [comment]
I know, but `sudo cowsay wat` anyway

**Pull request merged**
