### PR TITLE
Updated dropdown with reusable component and show on hover

### PR DESCRIPTION
**Pull request by yathomasi**
Updated the current dropdown implementation with the reusable component fix for https://github.com/iterative/iterative.ai/issues/370
Also, showing a dropdown on the hover fix for https://github.com/iterative/iterative.ai/issues/390

### CODE REVIEW

**Comment by yathomasi** [comment]
@iterative/websites
The outline color on focus doesn't match with the website, should we change it to `var(--color-light-blue-hover)`. Also, the outline is disabled for dropdown. If we want to keep it that way then should we consider showing the dropdown on focus?

**Comment by julieg18** [comment]
> @iterative/websites
> The outline color on focus doesn't match with the website, should we change it to `var(--color-light-blue-hover)`. 

Yes, the outline color should be updated! `--color-light-blue-hover` should work. 

> Also, the outline is disabled for dropdown. If we want to keep it that way then should we consider showing the dropdown on focus?

The the newest implementation, you should be able to turn on the dropdown outline again without any issues!

**Review by julieg18 — APPROVED** [review]
Looks great! Feel free to fix the outline color in this pr or in a separate one!

**Comment by yathomasi** [comment]
>Feel free to fix the outline color in this pr or in a separate one!

Sure, I will submit within this pr.

**Review by julieg18 — APPROVED** [review]
Looks great! Thanks for fixing the outline!

**Pull request merged**
